### ISSUE TITLE
Batch Event turns to null

### ISSUE THREAD

**Issue by harshsharma94** [flipkart-incubator/batchman#146]
Hi,
We are facing an issue with the a custom implementation of a Strategy wherein an EventData turns to null.
Attached below is the crashlog. Can you please go through it and suggest some measure.
As this repeatedly causes an exception whenever the data is flushed.

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.flipkart.batching.core.data.Tag.equals(java.lang.Object)' on a null object reference
       at com.flipkart.batching.core.data.TagData.equals(TagData.java:52)
       at java.util.ArrayList.indexOf(ArrayList.java:305)
       at java.util.ArrayList.contains(ArrayList.java:288)
       at com.flipkart.batching.persistence.TapePersistenceStrategy.removeData(TapePersistenceStrategy.java:101)
       at com.example.analytics.HybridBatchingStrategy.flush(HybridBatchingStrategy.java:63)
       at com.example.analytics..HybridBatchingStrategy$1.run(HybridBatchingStrategy.java:30)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.TinnoLoop(Looper.java:138)
       at android.os.Looper.loop(Looper.java:208)
       at android.os.HandlerThread.run(HandlerThread.java:61)

The HybridBatchingStrategy is similar to SizeTimeBatchingStrategy with the timer called every N seconds.
The exception is thrown everytime it tries to checks using .equals() method to remove data from strategy.

What we have observed is that the first event data gets turned into a reference with null event and null tag, which looks like below.
![batchman](https://user-images.githubusercontent.com/6527520/42632503-00c7e44c-85fb-11e8-84b8-5acb44a8d2e6.jpg)

Any help is appreciated.
Finally, thanks for this brilliant library. It saved a lot of our efforts.

**Comment by anirudhramanan** [comment]
Thanks for reaching out ! We will look into this issue. 

Can you share a unit test case for the same scenario if possible ?

**Comment by harshsharma94** [comment]
We had left this issue for a while.
But we again stumbled upon this issue.
One conclusion that we could reach was that cache file is updated with a different parent object instead of the expected object.

Initial cache file content:
{"tag":{"id":"low priority event id"},"event":{"cat":"x","act":"y","lbl":"z","ts":1532087011997},"eventId":16558900274774}   �{"tag":{"id":"low priority event id"},"event":{"cat":"a","act":"b","lbl":"c","ts":1532087021732}} 

Cache file on next session:
{"type":"TagBatch","value":{"tag":{"id":"low priority event id"},"dataCollection":{"dataCollection":[{"tag":{"id":"low priority event id"},"event":{"cat":"x","act":"y","lbl":"z","ts":1532087011997},"eventId":16558900274774},{"tag":{"id":"low priority event id"},"event":{"cat":"a","act":"b","lbl":"c","ts":1532087021732},"eventId":14314479856248}]}}}

It is overwritten by the TagBatch Object which is only referenced in onInitialized() method of TagBatchingStrategy, where a new instance of TagBatchObject is created. 

Also sometimes the file gets corrupt and all the events in PersistenceStrategy are cleared and after that maybe this object is getting written to cache file.

This is only possible in PersistedBatchReadyListener.java in the onReady() method. where we add it to file.

> PersistedBatchReadyListener.this.queueFile.add(batch);

**Comment by harshsharma94** [comment]
The reason for crash was same file path being shared by OnBatchReadyListener and PersistenceStrategy which we somehow missed during the initial implementation.
Thanks for the help.
